apiVersion: v1
kind: Service
metadata:
  name: arise-docs
  namespace: arise
spec:
  selector:
    app: arise-docs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer